version: 1.0.{build}
image: Visual Studio 2019
environment:
  matrix:
    - PYTHON: "C:\\Python311-x64"
    - PYTHON: "C:\\Python310-x64"
    - PYTHON: "C:\\Python39-x64"
    - PYTHON: "C:\\Python38-x64"
cache:
  - liblsl -> appveyor.yml

install:
  # Update PATH
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Upgrade pip, setuptools, wheel
  - "python -m pip install --upgrade pip"
  - "python --version"
  - "pip --version"
  # Download and unzip liblsl
  - "powershell Invoke-WebRequest -Uri 'https://github.com/sccn/liblsl/releases/download/v1.16.2/liblsl-1.16.2-Win_amd64.zip' -OutFile 'liblsl.zip'"
  - "unzip -o liblsl.zip -d liblsl"
  # Move DLL to correct directory
  - "move liblsl\\bin\\lsl.dll %PYTHON%\\Lib\\site-packages\\"
  # Set PYLSL_LIB environment variable
  - "set PYLSL_LIB=%PYTHON%\\Lib\\site-packages\\lsl.dll"
  # Uninstall and reinstall urllib3
  - "pip uninstall -y urllib3"
  - "pip install --upgrade urllib3>=2.0.5"
  # Install other dependencies
  - "pip install ."
  # Install pytest
  - "pip install pytest"
  # Exit if error
  - "if %errorlevel% neq 0 exit /b %errorlevel%"

build: off

test_script:
  - "echo 'About to run tests...'"
  # Set timeout for pytest (e.g., 300 seconds)--timeout=1000
  - "pytest Tests/"
  - "echo 'Finished running tests.'"
  - "if %errorlevel% neq 0 exit /b %errorlevel%"
