[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PyBCI"
authors = [{name = "Liam", email = "liambooth123@hotmail.co.uk"}]
dynamic = ["version", "description"]