author: !!python/tuple
- Liam Booth
author_email: !!python/tuple
- liambooth123@hotmail.co.uk
bdist_wheel: null
classifiers: '['
cmdclass: '{'
description: !!python/tuple
- A Python interface to create a BCI with the Lab Streaming Layer, scikit-learn and
  tensorflow packages
here: path.abspath(path.dirname(__name__))
install_requires: '['
keywords: !!python/tuple
- machine learning and data synchronisation on the Lab Streaming Layer
license: !!python/tuple
- MIT
long_description: long_description,
long_description_content_type: !!python/tuple
- text/markdown
name: !!python/tuple
- pybci
package_data: !!python/tuple
- {}
packages: !!python/tuple
- - pybci
python_requires: !!python/tuple
- '>=3.11'
url: !!python/tuple
- https://github.com/lmbooth/pybci
version: version['__version__'],
